# Generated by Django 4.1.3 on 2022-11-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='was_shown',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.BooleanField(),
        ),
    ]
