# Generated by Django 4.1.3 on 2022-12-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_imgsample_zv'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgsample',
            name='first',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imgsample',
            name='second',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
