# Generated by Django 4.1.3 on 2022-12-20 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_imgsample_first_imgsample_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.imgsample'),
        ),
    ]
