# Generated by Django 3.2.16 on 2023-01-09 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_answer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='colororder',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.imgsample'),
        ),
    ]
