# Generated by Django 3.2.16 on 2023-01-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_colororder_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Длительность в мс'),
        ),
    ]
