# Generated by Django 3.2.16 on 2023-01-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20230118_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='show_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='duration',
            field=models.IntegerField(default=2000, verbose_name='Длительность в мс'),
        ),
    ]
